@startuml

/'
ユースケース：ホテル情報を登録する

アクタ：
ホテルシステム管理者

目的：
ホテルシステム管理者が、新しいホテルの情報を
ホテル予約システムに登録する。

事前条件：
・ホテルシステム管理者がシステムを利用できる。
・登録対象となるホテルが、まだシステムに登録されていない。

事後条件：
・入力された新しいホテル情報がシステムに登録されている。
・登録済みのホテル情報一覧に、新しく登録したホテルが表示されている。

基本系列：
1. ホテルシステム管理者は、システムにアクセスする。

2. ホテル予約システムは、ホテル名、部屋種別、
   料金、定員の入力を促す。

3. ホテルシステム管理者は、新しく登録するホテル名、
   部屋種別、料金、定員を入力する。

4. ホテル予約システムは、入力された新しいホテル情報を登録する。

5. ホテル予約システムは、登録済みのすべてのホテル情報を表示する。

6. ホテルシステム管理者は、
   登録済みのすべてのホテル情報を閲覧する。
'/

title ホテル情報を登録する

skinparam shadowing false

skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
}

|ホテルシステム管理者|

start

:システムにアクセスする;

|ホテル予約システム|

:ホテル名、\n部屋種別、\n料金、定員の\n入力を促す;

|ホテルシステム管理者|

:新しく登録する\nホテル名、部屋種別、\n料金、定員を入力する;

|ホテル予約システム|

:入力された\n新しいホテル情報を\n登録する;

:登録済みの全ての\n情報を示す;

|ホテルシステム管理者|

:登録済みの\n全てのホテル情報を\n閲覧する;

stop

@enduml