@startuml

/'
ユースケース：チェックアウトする

アクタ：
フロント

目的：
フロントが利用者の宿泊情報を確認し、
料金の精算および部屋の鍵の返却を行ったうえで、
チェックアウト処理を完了する。

事前条件：
・利用者がチェックイン済みである。
・予約状態が CHECKED_IN である。
・利用者の宿泊情報がシステムに登録されている。

事後条件：
・利用者が料金を支払っている。
・フロントが部屋の鍵を受け取っている。
・予約状態が CHECKED_OUT になっている。
・宿泊していた部屋の状態が AVAILABLE になっている。

基本系列：
1. 利用者は、フロントにチェックアウトを申し出る。

2. フロントは、利用者の宿泊情報を確認する。

3. ホテル予約システムは、利用者が支払う料金を表示する。

4. 利用者は、表示された料金を支払う。

5. フロントは、利用者から料金を受領する。

6. フロントは、チェックアウトを確定する。

7. 利用者は、部屋の鍵をフロントに返却する。

8. フロントは、利用者から部屋の鍵を受け取る。

9. ホテル予約システムは、予約状態を
   CHECKED_OUT に設定する。

10. ホテル予約システムは、宿泊していた部屋の状態を
    AVAILABLE に設定する。
'/

title チェックアウトする

skinparam shadowing false

skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
}

|利用者|

start

:チェックアウトを\n申し出る;

|フロント|

:宿泊情報を確認する;

|ホテル予約システム|

:料金を表示する;

|利用者|

:料金を支払う;

|フロント|

:料金を受領する;

:チェックアウトを確定する;

|利用者|

:部屋の鍵を返却する;

|フロント|

:部屋の鍵を受け取る;

|ホテル予約システム|

:予約状態を\nCHECKED_OUTとする;

:部屋状態を\nAVAILABLEとする;

stop

@enduml