@startuml

/'
ユースケース：部屋を検索する

アクタ：
利用者

目的：
アクタが希望する場所、日程、人数のホテルの空き部屋を検索する。

事前条件：
なし

事後条件：
アクタが入力した条件を満たすホテルの空き部屋の一覧が表示されている。

基本系列：
1. アクタはシステム上で部屋を検索する旨を示す。
2. システムはアクタに場所、日程、人数の入力を促す。
3. アクタはシステム上で条件を入力する。
4. システムは入力された条件を満たす空き部屋種別の一覧を表示する。

代替系列：
4a. 入力された条件を満たす空き部屋が存在しない場合、
    システムは該当する空き部屋がないことを警告する。
'/

title 部屋を検索する

skinparam shadowing false
skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
  DiamondBackgroundColor #FFFDC4
  DiamondBorderColor Black
}

|利用者|

start

:「部屋を検索する」を選択する;

|ホテル予約システム|

:場所、日程、人数の入力を促す;

|利用者|

:場所、日程、人数を入力する;

|ホテル予約システム|

:入力された条件を満たす\n空き部屋種別を検索する;

if (該当する空き部屋があるか) then (ある)

  :空き部屋種別の一覧を表示する;

  |利用者|

  :空き部屋種別の一覧を確認する;

else (ない)

  |ホテル予約システム|

  :該当する空き部屋がないことを\n警告として表示する;

  |利用者|

  :警告を確認する;

endif

stop

@enduml