@startuml

/'
ユースケース：ホテルの情報を更新する

アクタ：
管理者

目的：
アクタが担当するホテルのホテル情報および部屋情報を更新する。

事前条件：
アクタに担当するホテルが割り振られている。

事後条件：
アクタが行った更新がホテル情報に反映されている。

基本系列：
1. アクタは、担当するホテルの情報をシステム上に表示する。

2. システムは、担当するホテルの現在の情報を表示する。

3. アクタは、ホテル情報を変更する。

4. システムは、入力された更新内容をホテル情報に反映する。

5. システムは、更新後のホテル情報を表示する。
'/

title ホテルの情報を更新する

skinparam shadowing false

skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
}

|管理者|

start

:担当するホテルの\n情報を表示する;

|ホテル予約システム|

:担当するホテルの\n現在の情報を表示する;

|管理者|

:ホテル名、住所、部屋種別、\n料金、定員などを変更する;

:更新内容を確定する;

|ホテル予約システム|

:入力された更新内容を\nホテル情報に反映する;

:更新後のホテル情報を表示する;

|管理者|

:更新後のホテル情報を確認する;

stop

@enduml