@startuml

/'
ユースケース：チェックインする

アクタ：
フロント

目的：
フロントが利用者の予約情報を確認し、
利用者に部屋を割り当ててチェックイン処理を行う。

事前条件：
・利用者が予約を行っている。
・利用者の予約情報がシステムに登録されている。
・予約状態が RESERVED である。
・予約した部屋種別に、割り当て可能な部屋が存在する。

事後条件：
・利用者に部屋が割り当てられている。
・予約状態が CHECKED_IN になっている。
・割り当てられた部屋の状態が OCCUPIED になっている。
・利用者が部屋の鍵を受け取っている。

基本系列：
1. 利用者は、予約情報をフロントに提示する。

2. フロントは、利用者から提示された予約情報を
   ホテル予約システムに入力する。

3. ホテル予約システムは、入力された予約情報を検索する。

4. ホテル予約システムは、該当する予約情報を表示する。

5. フロントは、表示された予約情報を確認し、
   チェックインを確定する。

6. ホテル予約システムは、利用者に割り当て可能な
   空いている部屋を割り当てる。

7. ホテル予約システムは、予約状態を
   CHECKED_IN に設定する。

8. ホテル予約システムは、割り当てた部屋の状態を
   OCCUPIED に設定する。

9. フロントは、利用者に割り当てられた部屋の鍵を渡す。

10. 利用者は、フロントから部屋の鍵を受け取る。
'/

title チェックインする

skinparam shadowing false

skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
}

|利用者|

start

:予約情報を\nフロントに提示する;

|フロント|

:予約情報を入力する;

|ホテル予約システム|

:予約情報を検索する;

:予約情報を表示する;

|フロント|

:チェックインを確定する;

|ホテル予約システム|

:利用者に空いている\n部屋を割り当てる;

:予約状況を\nCHECKED_INとする;

:部屋状態を\nOCCUPIEDとする;

|フロント|

:部屋の鍵を渡す;

|利用者|

:部屋の鍵を受け取る;

stop

@enduml