@startuml

/'
ユースケース：部屋を予約する
アクタ：利用者
目的：アクタが希望する種別と日程のホテルの部屋(種別)を予約する
事前条件：アクタが希望する日程とホテルの空き部屋(種別)が提示されている
事後条件：アクタが指定した種別の空室数が1減少している
　　　　　予約日時が記録されている
　　　　　予約状態をRESERVEDとする
基本系列
-1. アクタはシステム上で部屋(種別)を指定する
-2. システムは指定された部屋種別を予約し、予約日時を記録する。また予約状態をRESERVEDとする
-3. システムはアクタに対して予約された部屋種別の料金を示す
-4. アクタは表示された予約情報を確認する
'/

title 部屋を予約する

skinparam shadowing false
skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
}

|利用者|

start

:表示された部屋（種別）\n一覧から部屋（種別）\nを指定する;

|ホテル予約システム|

:部屋種別を予約し、\n予約日時を記録する;

:予約状態を\nRESERVEDとする;

:予約した部屋種別\nの料金を計算して\n表示する;

|利用者|

:予約した部屋種別の\n料金を閲覧する;

stop

@enduml