@startuml

/'
ユースケース：予約を確認する
アクタ：利用者
目的：アクタが自身の予約を確認する
事前条件：予約が完了している
事後条件：予約画面が表示されている
基本系列
-1. アクタはシステムにアクセスする
-2. アクタはシステム上で予約確認ボタンを押す
-3. システムは予約情報を表示する
-4. アクタは予約情報を確認する
'/

title 予約を確認する

skinparam shadowing false

skinparam activity {
  BackgroundColor #FFFDC4
  BorderColor Black
  FontColor Black
}

|利用者|

start

:システムにアクセスする;

:予約確認ボタンを押す;

|ホテル予約システム|

:予約情報を\n表示する;

|利用者|

:予約を閲覧する;

stop

@enduml